### ISSUE TITLE
face problem when letting camera detect image in my ipad

### ISSUE THREAD

**Issue by lxy200078** [Ali619/Object-Detection-Size-Measurement#2]
I did't print the image of aruco marker, I just use image in my ipad to let camera detect. It shows error below.
Traceback (most recent call last):
  File "c:/Users/lxy20/Desktop/Object-Detection-Size-Measurement-master/Object-Detection-Size-Measurement-master/measure_object_size_camera.py", line 35, in <module>
    contours = detector.detect_objects(img)
  File "c:\Users\lxy20\Desktop\Object-Detection-Size-Measurement-master\Object-Detection-Size-Measurement-master\object_detector.py", line 16, in detect_objects
    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
ValueError: too many values to unpack (expected 2)
[ WARN:0] terminating async callback

**Comment by Ali619** [comment]
> I did't print the image of aruco marker, I just use image in my ipad to let camera detect. It shows error below. Traceback (most recent call last): File "c:/Users/lxy20/Desktop/Object-Detection-Size-Measurement-master/Object-Detection-Size-Measurement-master/measure_object_size_camera.py", line 35, in contours = detector.detect_objects(img) File "c:\Users\lxy20\Desktop\Object-Detection-Size-Measurement-master\Object-Detection-Size-Measurement-master\object_detector.py", line 16, in detect_objects contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE) ValueError: too many values to unpack (expected 2) [ WARN:0] terminating async callback

Make sure to be installed `opencv-contrib-python` and not the `openCV` package. Also if you have both packages, they will interupt each other. So I suggest to start a new Venv enviroment and install `opencv-contrib-python` with `pip install opencv-contrib-python` command
